# basic options
title: GBLab
author: Yaseswini
#email: yaseswini.1404@gmail.com
#description: blah
#twitter_username: dont know
github_username:  Yaseswini

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
